info:
  app:
    name: Sample InApp Server
    version: 1.0.0

security:
  require-ssl: false

server:
  port: 8089
  url: "http://localhost:8089"
  servlet:
    session:
      timeout: 300
    context-path: "/mobileid-inapp"
  compression:
    enabled: true

spring:
  devtools:
    livereload:
      enabled: false

# CONFIGURABLE: Modify the values below as needed
sample:
  externalRef: "sampleUser"
  deviceName: "sampleDevice"

oidc:
# CONFIGURABLE: oidcBase may be modified if targeting an environment other than preprod.signicat.com. Contact Signicat for applicable values.
  oidcBase: "https://preprod.signicat.com/oidc/"
# CONFIGURABLE: clientID and scope may be modified to match the customer-specific setup. Contact Signicat for applicable values.
  clientId: "preprod.mobileid-sample.sampleapp"
  scope: "openid+profile+mobileid"
# CONFIGURABLE: redirect_uri
# Note! If you modify the redirect_uri, it will have to be configured by Signicat. Contact Signicat if this is the case. For INAPP operation, the mobile device must have connectivity to the host for the redirectURI.
  redirectUri: "http://localhost:8089/mobileid-inapp/consumeOidc"
# CONFIGURABLE: Values for the different methods may be modified to match the customer-specific setup. Contact Signicat for the applicable value.
  acrValues: "urn:signicat:oidc:method:"
  regMethod: "mobileid-inapp-reg"
  authMethod: "mobileid-inapp-auth"
  consentSignMethod: "mobileid-inapp-consent-sign"
# CONFIGURABLE: cred64 may be modified to match the customer-specific setup. Contact Signicat for the applicable value.
# Note! The cred64 value is derived from "clientID:clientSecret" and is base64-encoded.
  cred64: "cHJlcHJvZC5tb2JpbGVpZC1zYW1wbGUuc2FtcGxlYXBwOm1xWi1fNzUtZjJ3TnNpUVRPTmI3T240YUFaN3pjMjE4bXJSVmsxb3VmYTg="

ws:
# CONFIGURABLE: scidWsUrl may be modified if targeting another environment or another version of the webservice. Contact Signicat for applicable values.
  scidWsUrl: "https://preprod.signicat.com/ws/scid-v2"
# CONFIGURABLE: service and domain. May be modified to match the customer-specific setup. Contact Signicat for applicable values.
  service: "mobileid-sample"
  domain: "default"
# CONFIGURABLE: apiKey may be modified to match the customer-specific setup. Contact Signicat for the applicable value.
# Note! This value matches the webservice password for the service.
  apiKey: "Bond007"


