info:
  app:
    name: Sample InApp Server
    version: 1.0.0

security:
  require-ssl: false

server:
  port: 8089
  url: "http://localhost:8089"
  servlet:
    session:
      timeout: 300
    context-path: "/mobileid-inapp"
  compression:
    enabled: true

spring:
  devtools:
    livereload:
      enabled: false

# TODO: Change to YOUR sample user and device name
sample:
  externalRef: "sampleUser"
  deviceName: "sampleDeviceName"

oidc:
  oidcBase: "https://preprod.signicat.com/oidc/"
  clientId: "preprod-evli.fi-mobileid"
  scope: "openid+profile+mobileid"
  # TODO!: Change redirect_uri
  # Note! This redirect_uri has to be configured on Signicat side
  #redirectUri: "http://localhost:8089/callback"
  redirectUri: "http://localhost:8089/mobileid-inapp/consumeOidc"

  acrValues: "urn:signicat:oidc:method:"
  regMethod: "mobileid-inapp-mobile-reg"
  authMethod: "mobileid-inapp-mobile-auth"
  consentSignMethod: "mobileid-inapp-web-sign"
  cred64: "cHJlcHJvZC1ldmxpLmZpLW1vYmlsZWlkOmpmS0JqVnotaGNsYWpUUDlzQmxPMnNnNFhaTzFsd2lRenh1NldjR1V4cjg="

ws:
  scidWsUrl: "https://preprod.signicat.com/ws/scid-v2"
  service: "evli.fi"
  domain: "default"
  apiKey: "Bond007"

# configure this if you are using a Signicat MobileID microservice
microservice:
  #baseUrl: "http://localhost:9001/"
  #baseUrl: "https://dev01.signicat.com/"
  baseUrl: "http://mobileidsrv.dev.signicat.com/"
  contextPath: "mobileidsrv/"
