
info:
  app:
    name: Sample InApp Server
    version: 1.0.0

security:
  require-ssl: false

server:
  port: 8089
  url: "http://localhost:8089"
  servlet:
    session:
      timeout: 300
    context-path: "/mobileid-inapp"
  compression:
    enabled: true

spring:
  devtools:
    livereload:
      enabled: false

# TODO: Change to YOUR sample user and device name
sample:
  externalRef: "sampleMisa"
  deviceName: "sampleDevice"

oidc:
  oidcBase: "https://qa.signicat.com/oidc/"
  clientId: "qa.signicat.sampleapp"
  scope: "openid+profile+mobileid"
# TODO!: Change redirect_uri
# Note! This redirect_uri has to be configured on Signicat side
  redirectUri: "http://localhost:8089/consumeOidc"
  acrValues: "urn:signicat:oidc:method:"
  regMethod: "mobileid-inapp-mobile-reg"
  authMethod: "mobileid-inapp-mobile-auth"
  consentSignMethod: "mobileid-inapp-web-sign"
  cred64: "cWEuc2lnbmljYXQuc2FtcGxlYXBwOm9MaUxqVjNJSDR0eGg4U0NKNkNMd190UGhIMjUzTzc4S3hrZlppUTZOODA="

ws:
  scidWsUrl: "https://qa.signicat.com/ws/scid-v2"
  service: "signicat"
  domain: "default"
  apiKey: "Bond007"

# configure this if you are using a Signicat MobileID microservice
microservice:
  #baseUrl: "http://localhost:9001/"
  baseUrl: "https://qa.signicat.com/"
  contextPath: "mobileidsrv/"

